"""Baseline schema.

Single-revision baseline for the whole Football-IQ schema: 46 tables, 20 enum
types, 87 foreign keys, and the pgvector extension plus its two ivfflat ANN
indexes. It replaces the previous 33-revision chain, which had branched at 0002
and been re-merged by ``0003_merge`` and carried raw SQL in 22 of its 33 files.

There is no upgrade path from the old chain -- this is a from-scratch baseline
for a fresh database, which is what the platform re-provisioning called for.

``app/models.py`` is the source of truth: ``alembic revision --autogenerate``
against a database at this revision reports **no** changes. Keep it that way --
if autogenerate starts emitting diffs, the models and the schema have drifted.

Three things here are *not* autogenerated and must be maintained by hand:

* ``CREATE EXTENSION vector`` -- must run before any ``Vector(...)`` column DDL.
* The enum types -- Postgres enums are database-level objects shared across
  tables, so they are declared once below and created/dropped explicitly rather
  than inline per ``create_table`` (which would fail on the second table to use
  a given type).
* ``clips_job_id_fkey`` / ``clips_calibration_version_id_fkey`` -- declared
  ``use_alter=True`` on the model to break the ``clips -> processing_jobs ->
  clips`` and ``clips -> field_calibrations -> processing_jobs -> clips`` create
  cycles. Autogenerate omits them from ``create_table`` but does not emit the
  follow-up ALTER, so they are added at the end of ``upgrade()``.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-25

"""

from collections.abc import Sequence

import app.types
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── Enum types ────────────────────────────────────────────────────────────────
# Postgres enums are database-level objects shared by every table that
# references them, so they are declared once here with create_type=False and
# created/dropped explicitly in upgrade()/downgrade().
active_learning_reason_enum = postgresql.ENUM(
    "low_confidence",
    "uncertainty_sampling",
    "regression",
    "hard_negative",
    name="active_learning_reason",
    create_type=False,
)
active_learning_status_enum = postgresql.ENUM(
    "queued",
    "in_review",
    "resolved",
    name="active_learning_status",
    create_type=False,
)
alert_severity_enum = postgresql.ENUM(
    "low",
    "medium",
    "high",
    name="alert_severity",
    create_type=False,
)
alert_type_enum = postgresql.ENUM(
    "bio_deviation",
    "effort_anomaly",
    "formation_anomaly",
    "formation_tendency",
    "workload_risk",
    name="alert_type",
    create_type=False,
)
capture_regime_enum = postgresql.ENUM(
    "drone_follow",
    "fixed_sideline",
    "unconstrained",
    "unknown",
    name="capture_regime",
    create_type=False,
)
cfbd_sync_status_enum = postgresql.ENUM(
    "running",
    "succeeded",
    "failed",
    "partial",
    name="cfbd_sync_status",
    create_type=False,
)
correction_type_enum = postgresql.ENUM(
    "clip_boundary",
    "player_identity",
    "event_tag",
    "formation_tag",
    "route_tag",
    "coverage_tag",
    "personnel_tag",
    "leverage_tag",
    "effort_tag",
    "pose_biomechanics_tag",
    name="correction_type",
    create_type=False,
)
job_status_enum = postgresql.ENUM(
    "queued",
    "running",
    "succeeded",
    "failed",
    "cancelled",
    name="job_status",
    create_type=False,
)
job_type_enum = postgresql.ENUM(
    "pipeline",
    "ingest",
    "segment",
    "calibrate",
    "detect",
    "track",
    "reid",
    "pose",
    "events",
    "labels",
    "metrics",
    "pressure",
    "render",
    "render_hls",
    "routes",
    "coverage",
    "oline",
    "self_scout",
    "embeddings",
    "workload_rollup",
    "train",
    name="job_type",
    create_type=False,
)
model_stage_enum = postgresql.ENUM(
    "experimental",
    "staging",
    "production",
    "retired",
    name="model_stage",
    create_type=False,
)
player_identity_state_enum = postgresql.ENUM(
    "known",
    "probable",
    "unknown",
    "conflicting",
    "needs_review",
    name="player_identity_state",
    create_type=False,
)
player_visibility_state_enum = postgresql.ENUM(
    "staff_only",
    "player_approved",
    "recruiting_approved",
    "archived",
    name="player_visibility_state",
    create_type=False,
)
profile_generation_source_enum = postgresql.ENUM(
    "manual",
    "model_assisted",
    "imported",
    name="profile_generation_source",
    create_type=False,
)
report_format_enum = postgresql.ENUM(
    "pdf",
    "csv",
    "json",
    name="report_format",
    create_type=False,
)
session_kind_enum = postgresql.ENUM(
    "practice",
    "scrimmage",
    "game",
    name="session_kind",
    create_type=False,
)
side_of_ball_enum = postgresql.ENUM(
    "offense",
    "defense",
    "special_teams",
    name="side_of_ball",
    create_type=False,
)
snapshot_approval_status_enum = postgresql.ENUM(
    "pending",
    "approved",
    "rejected",
    name="snapshot_approval_status",
    create_type=False,
)
source_type_enum = postgresql.ENUM(
    "drone",
    "uploaded_clip",
    name="source_type",
    create_type=False,
)
user_role_enum = postgresql.ENUM(
    "admin",
    "analyst",
    "coach",
    "sportsperformance",
    "player",
    "viewer",
    name="user_role",
    create_type=False,
)
video_status_enum = postgresql.ENUM(
    "uploaded",
    "processing",
    "ready",
    "failed",
    name="video_status",
    create_type=False,
)

ALL_ENUMS = (
    active_learning_reason_enum,
    active_learning_status_enum,
    alert_severity_enum,
    alert_type_enum,
    capture_regime_enum,
    cfbd_sync_status_enum,
    correction_type_enum,
    job_status_enum,
    job_type_enum,
    model_stage_enum,
    player_identity_state_enum,
    player_visibility_state_enum,
    profile_generation_source_enum,
    report_format_enum,
    session_kind_enum,
    side_of_ball_enum,
    snapshot_approval_status_enum,
    source_type_enum,
    user_role_enum,
    video_status_enum,
)


def upgrade() -> None:
    bind = op.get_bind()
    # pgvector must exist before any Vector(...) column DDL is emitted.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    op.create_table(
        "cfbd_drives",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_drive_id", sa.BigInteger(), nullable=False),
        sa.Column("cfbd_game_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("offense", sa.String(length=120), nullable=True),
        sa.Column("offense_conference", sa.String(length=120), nullable=True),
        sa.Column("defense", sa.String(length=120), nullable=True),
        sa.Column("defense_conference", sa.String(length=120), nullable=True),
        sa.Column("drive_number", sa.Integer(), nullable=True),
        sa.Column("scoring", sa.Boolean(), nullable=True),
        sa.Column("start_period", sa.Integer(), nullable=True),
        sa.Column("end_period", sa.Integer(), nullable=True),
        sa.Column("plays", sa.Integer(), nullable=True),
        sa.Column("yards", sa.Integer(), nullable=True),
        sa.Column("drive_result", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cfbd_drive_id", name="uq_cfbd_drives_source_id"),
    )
    op.create_index(
        op.f("ix_cfbd_drives_cfbd_drive_id"), "cfbd_drives", ["cfbd_drive_id"], unique=False
    )
    op.create_index(
        op.f("ix_cfbd_drives_cfbd_game_id"), "cfbd_drives", ["cfbd_game_id"], unique=False
    )
    op.create_index(op.f("ix_cfbd_drives_defense"), "cfbd_drives", ["defense"], unique=False)
    op.create_index(op.f("ix_cfbd_drives_offense"), "cfbd_drives", ["offense"], unique=False)
    op.create_index(op.f("ix_cfbd_drives_season"), "cfbd_drives", ["season"], unique=False)
    op.create_table(
        "cfbd_games",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_game_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("season_type", sa.String(length=32), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("neutral_site", sa.Boolean(), nullable=True),
        sa.Column("conference_game", sa.Boolean(), nullable=True),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("home_id", sa.BigInteger(), nullable=True),
        sa.Column("home_team", sa.String(length=120), nullable=True),
        sa.Column("home_conference", sa.String(length=120), nullable=True),
        sa.Column("home_points", sa.Integer(), nullable=True),
        sa.Column("away_id", sa.BigInteger(), nullable=True),
        sa.Column("away_team", sa.String(length=120), nullable=True),
        sa.Column("away_conference", sa.String(length=120), nullable=True),
        sa.Column("away_points", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cfbd_game_id", name="uq_cfbd_games_source_id"),
    )
    op.create_index(op.f("ix_cfbd_games_away_team"), "cfbd_games", ["away_team"], unique=False)
    op.create_index(
        op.f("ix_cfbd_games_cfbd_game_id"), "cfbd_games", ["cfbd_game_id"], unique=False
    )
    op.create_index(op.f("ix_cfbd_games_home_team"), "cfbd_games", ["home_team"], unique=False)
    op.create_index(op.f("ix_cfbd_games_season"), "cfbd_games", ["season"], unique=False)
    op.create_index(op.f("ix_cfbd_games_season_type"), "cfbd_games", ["season_type"], unique=False)
    op.create_index(op.f("ix_cfbd_games_week"), "cfbd_games", ["week"], unique=False)
    op.create_table(
        "cfbd_plays",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_play_id", sa.BigInteger(), nullable=False),
        sa.Column("cfbd_game_id", sa.BigInteger(), nullable=True),
        sa.Column("cfbd_drive_id", sa.BigInteger(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("season_type", sa.String(length=32), nullable=True),
        sa.Column("offense", sa.String(length=120), nullable=True),
        sa.Column("offense_conference", sa.String(length=120), nullable=True),
        sa.Column("defense", sa.String(length=120), nullable=True),
        sa.Column("defense_conference", sa.String(length=120), nullable=True),
        sa.Column("home", sa.String(length=120), nullable=True),
        sa.Column("away", sa.String(length=120), nullable=True),
        sa.Column("period", sa.Integer(), nullable=True),
        sa.Column("yard_line", sa.Integer(), nullable=True),
        sa.Column("down", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("yards_gained", sa.Integer(), nullable=True),
        sa.Column("play_type", sa.String(length=120), nullable=True),
        sa.Column("play_text", sa.Text(), nullable=True),
        sa.Column("ppa", sa.Float(), nullable=True),
        sa.Column("scoring", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cfbd_play_id", name="uq_cfbd_plays_source_id"),
    )
    op.create_index(
        op.f("ix_cfbd_plays_cfbd_drive_id"), "cfbd_plays", ["cfbd_drive_id"], unique=False
    )
    op.create_index(
        op.f("ix_cfbd_plays_cfbd_game_id"), "cfbd_plays", ["cfbd_game_id"], unique=False
    )
    op.create_index(
        op.f("ix_cfbd_plays_cfbd_play_id"), "cfbd_plays", ["cfbd_play_id"], unique=False
    )
    op.create_index(op.f("ix_cfbd_plays_defense"), "cfbd_plays", ["defense"], unique=False)
    op.create_index(op.f("ix_cfbd_plays_offense"), "cfbd_plays", ["offense"], unique=False)
    op.create_index(op.f("ix_cfbd_plays_season"), "cfbd_plays", ["season"], unique=False)
    op.create_index(op.f("ix_cfbd_plays_week"), "cfbd_plays", ["week"], unique=False)
    op.create_table(
        "cfbd_sync_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("season_type", sa.String(length=32), nullable=True),
        sa.Column("status", cfbd_sync_status_enum, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cfbd_sync_runs_endpoint"), "cfbd_sync_runs", ["endpoint"], unique=False
    )
    op.create_index(op.f("ix_cfbd_sync_runs_season"), "cfbd_sync_runs", ["season"], unique=False)
    op.create_table(
        "cfbd_team_game_stats",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_game_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("season_type", sa.String(length=32), nullable=True),
        sa.Column("team", sa.String(length=120), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=True),
        sa.Column("conference", sa.String(length=120), nullable=True),
        sa.Column("opponent", sa.String(length=120), nullable=True),
        sa.Column("home_away", sa.String(length=8), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cfbd_game_id", "team", name="uq_cfbd_team_game_stats_game_team"),
    )
    op.create_index(
        op.f("ix_cfbd_team_game_stats_cfbd_game_id"),
        "cfbd_team_game_stats",
        ["cfbd_game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cfbd_team_game_stats_conference"),
        "cfbd_team_game_stats",
        ["conference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cfbd_team_game_stats_opponent"), "cfbd_team_game_stats", ["opponent"], unique=False
    )
    op.create_index(
        op.f("ix_cfbd_team_game_stats_season"), "cfbd_team_game_stats", ["season"], unique=False
    )
    op.create_index(
        op.f("ix_cfbd_team_game_stats_team"), "cfbd_team_game_stats", ["team"], unique=False
    )
    op.create_table(
        "cfbd_teams",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_team_id", sa.BigInteger(), nullable=False),
        sa.Column("school", sa.String(length=120), nullable=False),
        sa.Column("mascot", sa.String(length=120), nullable=True),
        sa.Column("abbreviation", sa.String(length=32), nullable=True),
        sa.Column("conference", sa.String(length=120), nullable=True),
        sa.Column("division", sa.String(length=120), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("alt_color", sa.String(length=32), nullable=True),
        sa.Column("logos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cfbd_team_id", name="uq_cfbd_teams_source_id"),
    )
    op.create_index(
        op.f("ix_cfbd_teams_cfbd_team_id"), "cfbd_teams", ["cfbd_team_id"], unique=False
    )
    op.create_index(op.f("ix_cfbd_teams_conference"), "cfbd_teams", ["conference"], unique=False)
    op.create_index(op.f("ix_cfbd_teams_school"), "cfbd_teams", ["school"], unique=False)
    op.create_table(
        "cfbd_win_probability",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cfbd_game_id", sa.BigInteger(), nullable=False),
        sa.Column("play_id", sa.BigInteger(), nullable=True),
        sa.Column("play_number", sa.Integer(), nullable=False),
        sa.Column("home", sa.String(length=120), nullable=True),
        sa.Column("away", sa.String(length=120), nullable=True),
        sa.Column("home_id", sa.BigInteger(), nullable=True),
        sa.Column("away_id", sa.BigInteger(), nullable=True),
        sa.Column("spread", sa.Float(), nullable=True),
        sa.Column("home_ball", sa.Boolean(), nullable=True),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("time_remaining", sa.Integer(), nullable=True),
        sa.Column("yard_line", sa.Integer(), nullable=True),
        sa.Column("down", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("home_win_prob", sa.Float(), nullable=True),
        sa.Column("play_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cfbd_game_id", "play_number", name="uq_cfbd_win_probability_game_play"
        ),
    )
    op.create_index(
        op.f("ix_cfbd_win_probability_cfbd_game_id"),
        "cfbd_win_probability",
        ["cfbd_game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cfbd_win_probability_play_id"), "cfbd_win_probability", ["play_id"], unique=False
    )
    op.create_table(
        "opponent_priors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("opponent_team", sa.String(length=120), nullable=True),
        sa.Column("down", sa.Integer(), nullable=True),
        sa.Column("distance_bucket", sa.String(length=16), nullable=True),
        sa.Column("field_zone", sa.String(length=16), nullable=True),
        sa.Column("alpha_pass", sa.Float(), nullable=False),
        sa.Column("alpha_run", sa.Float(), nullable=False),
        sa.Column("n_pass", sa.Integer(), nullable=False),
        sa.Column("n_run", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "opponent_team",
            "down",
            "distance_bucket",
            "field_zone",
            name="opponent_priors_situation_uq",
        ),
    )
    op.create_index(
        op.f("ix_opponent_priors_opponent_team"), "opponent_priors", ["opponent_team"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", user_role_enum, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "academic_calendar_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="manual_csv", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_academic_calendar_events_date"), "academic_calendar_events", ["date"], unique=False
    )
    op.create_table(
        "playbook_concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("structure_kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assignments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coaching_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playbook_concepts_name"), "playbook_concepts", ["name"], unique=True)
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.Column("position_group", sa.String(length=20), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "visibility_state",
            player_visibility_state_enum,
            server_default="staff_only",
            nullable=False,
        ),
        sa.Column("visibility_updated_by", sa.UUID(), nullable=True),
        sa.Column("visibility_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["visibility_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_position_group"), "players", ["position_group"], unique=False)
    op.create_table(
        "report_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_type", sa.String(length=64), nullable=False),
        sa.Column("format", report_format_enum, nullable=False),
        sa.Column("status", job_status_enum, nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_uri", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_jobs_created_at"), "report_jobs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_report_jobs_report_type"), "report_jobs", ["report_type"], unique=False
    )
    op.create_index(
        op.f("ix_report_jobs_requested_by"), "report_jobs", ["requested_by"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "training_datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "snapshot_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("model_scope", sa.String(length=100), nullable=False),
        sa.Column("source_label_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_correction_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column("changelog", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_datasets_model_scope"), "training_datasets", ["model_scope"], unique=False
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("status", video_status_enum, nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("codec", sa.String(length=50), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_kind", session_kind_enum, nullable=True),
        sa.Column("source_type", source_type_enum, nullable=True),
        sa.Column("opponent_team", sa.String(length=120), nullable=True),
        sa.Column("practice_session_id", sa.UUID(), nullable=True),
        sa.Column("our_possession", side_of_ball_enum, nullable=True),
        sa.Column("capture_regime", capture_regime_enum, nullable=True),
        sa.Column("regime_confidence", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_capture_regime"), "videos", ["capture_regime"], unique=False)
    op.create_index(op.f("ix_videos_opponent_team"), "videos", ["opponent_team"], unique=False)
    op.create_index(
        op.f("ix_videos_practice_session_id"), "videos", ["practice_session_id"], unique=False
    )
    op.create_index(op.f("ix_videos_recorded_at"), "videos", ["recorded_at"], unique=False)
    op.create_index(op.f("ix_videos_session_kind"), "videos", ["session_kind"], unique=False)
    op.create_table(
        "gps_workload_daily",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("session_type", sa.String(length=30), server_default="practice", nullable=False),
        sa.Column("total_distance_m", sa.Float(), nullable=True),
        sa.Column("high_speed_distance_m", sa.Float(), nullable=True),
        sa.Column("sprint_count", sa.Integer(), nullable=True),
        sa.Column("max_speed_ms", sa.Float(), nullable=True),
        sa.Column("accel_count", sa.Integer(), nullable=True),
        sa.Column("decel_count", sa.Integer(), nullable=True),
        sa.Column("player_load", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="manual_csv", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "date", "session_type", name="gps_workload_daily_unique"),
    )
    op.create_index(
        op.f("ix_gps_workload_daily_date"), "gps_workload_daily", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_gps_workload_daily_player_id"), "gps_workload_daily", ["player_id"], unique=False
    )
    op.create_table(
        "injury_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("reported_date", sa.Date(), nullable=False),
        sa.Column("body_region", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("days_missed", sa.Integer(), nullable=True),
        sa.Column("restricted", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.String(length=50), server_default="manual_csv", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_injury_history_player_id"), "injury_history", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_injury_history_reported_date"), "injury_history", ["reported_date"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("training_dataset_id", sa.UUID(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("promoted_stage", model_stage_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["training_dataset_id"], ["training_datasets.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_versions_model_name"), "model_versions", ["model_name"], unique=False
    )
    op.create_table(
        "player_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("role_summary", sa.Text(), nullable=True),
        sa.Column("development_goals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.Column("player_summary", sa.Text(), nullable=True),
        sa.Column("benchmark_group", sa.String(length=40), nullable=True),
        sa.Column("favorite_clip_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "generated_by", profile_generation_source_enum, server_default="manual", nullable=False
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "restricted_context_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "season", name="player_profiles_player_season_uq"),
    )
    op.create_index(
        op.f("ix_player_profiles_player_id"), "player_profiles", ["player_id"], unique=False
    )
    op.create_table(
        "player_visibility_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("previous_state", player_visibility_state_enum, nullable=True),
        sa.Column("next_state", player_visibility_state_enum, nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_visibility_audit_player_id"),
        "player_visibility_audit",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "player_workload_daily",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("daily_load", sa.Float(), nullable=True),
        sa.Column("sprint_count", sa.Integer(), nullable=True),
        sa.Column("max_speed_yps", sa.Float(), nullable=True),
        sa.Column("asymmetry_index", sa.Float(), nullable=True),
        sa.Column("acute_load_7d", sa.Float(), nullable=True),
        sa.Column("chronic_load_28d", sa.Float(), nullable=True),
        sa.Column("acwr", sa.Float(), nullable=True),
        sa.Column("injury_risk_score", sa.Float(), nullable=True),
        sa.Column("risk_reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("clip_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attribution", sa.String(length=20), server_default="player", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_variant", sa.String(length=50), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "date", name="player_workload_daily_unique"),
    )
    op.create_index(
        op.f("ix_player_workload_daily_date"), "player_workload_daily", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_player_workload_daily_player_id"),
        "player_workload_daily",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "sc_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("session_volume", sa.Float(), nullable=True),
        sa.Column("tonnage_kg", sa.Float(), nullable=True),
        sa.Column("session_rpe", sa.Float(), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="manual_csv", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "date", name="sc_sessions_unique"),
    )
    op.create_index(op.f("ix_sc_sessions_date"), "sc_sessions", ["date"], unique=False)
    op.create_index(op.f("ix_sc_sessions_player_id"), "sc_sessions", ["player_id"], unique=False)
    op.create_table(
        "wellness_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("soreness", sa.Integer(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="manual_csv", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "date", name="wellness_entries_unique"),
    )
    op.create_index(op.f("ix_wellness_entries_date"), "wellness_entries", ["date"], unique=False)
    op.create_index(
        op.f("ix_wellness_entries_player_id"), "wellness_entries", ["player_id"], unique=False
    )
    op.create_table(
        "clips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("play_number", sa.Integer(), nullable=True),
        sa.Column("play_call_id", sa.String(length=100), nullable=True),
        sa.Column("label_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("boundary_source", sa.String(length=20), nullable=True),
        sa.Column("boundary_confidence", sa.Float(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("calibration_version_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("personnel_grouping", sa.String(length=20), nullable=True),
        sa.Column("down", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("field_zone", sa.String(length=30), nullable=True),
        sa.Column("session_kind", session_kind_enum, nullable=True),
        sa.Column("our_possession", side_of_ball_enum, nullable=True),
        sa.Column("side_of_ball", side_of_ball_enum, nullable=True),
        sa.Column("capture_regime", capture_regime_enum, nullable=True),
        sa.Column("regime_confidence", sa.Float(), nullable=True),
        sa.Column("uncertainty_score", sa.Float(), nullable=True),
        sa.Column(
            "uncertainty_calibrated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("result_state", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calibration_version_id"],
            ["field_calibrations.id"],
            name="clips_calibration_version_id_fkey",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["processing_jobs.id"],
            name="clips_job_id_fkey",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clips_capture_regime"), "clips", ["capture_regime"], unique=False)
    op.create_index(op.f("ix_clips_play_call_id"), "clips", ["play_call_id"], unique=False)
    op.create_index(op.f("ix_clips_result_state"), "clips", ["result_state"], unique=False)
    op.create_index(op.f("ix_clips_session_kind"), "clips", ["session_kind"], unique=False)
    op.create_index(op.f("ix_clips_side_of_ball"), "clips", ["side_of_ball"], unique=False)
    op.create_index(
        op.f("ix_clips_uncertainty_score"), "clips", ["uncertainty_score"], unique=False
    )
    op.create_index(op.f("ix_clips_video_id"), "clips", ["video_id"], unique=False)
    op.create_table(
        "embedding_cluster_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("cluster_label", sa.String(length=64), nullable=False),
        sa.Column("proposed_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("member_clip_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("centroid", app.types.Vector(256), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("cohesion_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_experimental", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("accepted_label_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embedding_cluster_proposals_status"),
        "embedding_cluster_proposals",
        ["status"],
        unique=False,
    )
    op.create_table(
        "player_profile_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("summary_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("development_focus", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_clip_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "identity_state",
            player_identity_state_enum,
            server_default="needs_review",
            nullable=False,
        ),
        sa.Column("identity_confidence", sa.Float(), nullable=True),
        sa.Column("identity_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "generated_by",
            profile_generation_source_enum,
            server_default="model_assisted",
            nullable=False,
        ),
        sa.Column(
            "approval_status",
            snapshot_approval_status_enum,
            server_default="pending",
            nullable=False,
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "experimental_flag", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["player_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_profile_snapshots_player_id"),
        "player_profile_snapshots",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_profile_snapshots_profile_id"),
        "player_profile_snapshots",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_profile_snapshots_week_start"),
        "player_profile_snapshots",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "assignment_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=False),
        sa.Column("assignment_key", sa.String(length=64), nullable=False),
        sa.Column("grade", sa.String(length=24), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), server_default="0", nullable=False),
        sa.Column("uncertainty", sa.Float(), server_default="1", nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("experimental", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="auto", nullable=False),
        sa.Column("coach_grade", sa.String(length=24), nullable=True),
        sa.Column("coach_comment", sa.Text(), nullable=True),
        sa.Column("overridden_by", sa.UUID(), nullable=True),
        sa.Column("overridden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["concept_id"], ["playbook_concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["overridden_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "clip_id", "concept_id", "assignment_key", name="assignment_scores_unique"
        ),
    )
    op.create_index(
        op.f("ix_assignment_scores_clip_id"), "assignment_scores", ["clip_id"], unique=False
    )
    op.create_index(
        op.f("ix_assignment_scores_concept_id"), "assignment_scores", ["concept_id"], unique=False
    )
    op.create_table(
        "clip_players",
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("clip_id", "player_id"),
    )
    op.create_table(
        "coach_corrections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("correction_type", correction_type_enum, nullable=False),
        sa.Column("original_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("corrected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_by", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("training_eligible", sa.Boolean(), nullable=False),
        sa.Column("exported_as_label", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["corrected_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coach_corrections_clip_id"), "coach_corrections", ["clip_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=True),
        sa.Column("timestamp_seconds", sa.Float(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_clip_id"), "events", ["clip_id"], unique=False)
    op.create_table(
        "play_concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="coach", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("assignment_player_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["concept_id"], ["playbook_concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clip_id", "concept_id", name="play_concepts_clip_concept_uq"),
    )
    op.create_index(op.f("ix_play_concepts_clip_id"), "play_concepts", ["clip_id"], unique=False)
    op.create_index(
        op.f("ix_play_concepts_concept_id"), "play_concepts", ["concept_id"], unique=False
    )
    op.create_table(
        "play_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("play_id", sa.UUID(), nullable=True),
        sa.Column("opponent_team", sa.String(length=120), nullable=True),
        sa.Column("signal_vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logit_score", sa.Float(), nullable=True),
        sa.Column("predicted_class", sa.String(length=32), nullable=True),
        sa.Column("true_class", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("calibrated_prob", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.Float(), nullable=True),
        sa.Column("is_calibrated", sa.Boolean(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_play_predictions_clip_id"), "play_predictions", ["clip_id"], unique=False
    )
    op.create_index(
        op.f("ix_play_predictions_opponent_team"),
        "play_predictions",
        ["opponent_team"],
        unique=False,
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("clip_id", sa.UUID(), nullable=True),
        sa.Column("job_type", job_type_enum, nullable=False),
        sa.Column("status", job_status_enum, nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("pipeline_mode", sa.String(length=20), nullable=True),
        sa.Column("leased_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_stage", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("nightly_followup_job_id", sa.UUID(), nullable=True),
        sa.Column("input_artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("training_dataset_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["training_dataset_id"], ["training_datasets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_processing_jobs_claim",
        "processing_jobs",
        [sa.literal_column("priority DESC"), "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'::job_status"),
    )
    op.create_index(
        op.f("ix_processing_jobs_pipeline_mode"), "processing_jobs", ["pipeline_mode"], unique=False
    )
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_processing_jobs_video_id"), "processing_jobs", ["video_id"], unique=False
    )
    op.create_table(
        "active_learning_queue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=True),
        sa.Column("label_type", sa.String(length=100), nullable=False),
        sa.Column("queue_reason", active_learning_reason_enum, nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("model_confidence", sa.Float(), nullable=True),
        sa.Column("source_model_version_id", sa.UUID(), nullable=True),
        sa.Column("correction_id", sa.UUID(), nullable=True),
        sa.Column("status", active_learning_status_enum, nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["correction_id"], ["coach_corrections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_model_version_id"], ["model_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_active_learning_queue_clip_id"), "active_learning_queue", ["clip_id"], unique=False
    )
    op.create_index(
        op.f("ix_active_learning_queue_label_type"),
        "active_learning_queue",
        ["label_type"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("clip_id", sa.UUID(), nullable=True),
        sa.Column("position_group", sa.String(length=20), nullable=False),
        sa.Column("alert_type", alert_type_enum, nullable=False),
        sa.Column("severity", alert_severity_enum, nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deviation_sd", sa.Float(), nullable=True),
        sa.Column("clip_uri", sa.Text(), nullable=True),
        sa.Column("period_name", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_actioned", sa.Boolean(), nullable=False),
        sa.Column("actioned_by", sa.UUID(), nullable=True),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["actioned_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_clip_id"), "alerts", ["clip_id"], unique=False)
    op.create_index(op.f("ix_alerts_player_id"), "alerts", ["player_id"], unique=False)
    op.create_index(op.f("ix_alerts_position_group"), "alerts", ["position_group"], unique=False)
    op.create_index(op.f("ix_alerts_session_id"), "alerts", ["session_id"], unique=False)
    op.create_table(
        "field_calibrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("homography", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("confidence_threshold", sa.Float(), nullable=False),
        sa.Column("analytics_safe", sa.Boolean(), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("calibration_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("kalman_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("inlier_ratio", sa.Float(), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("parallel_variance", sa.Float(), nullable=True),
        sa.Column("temporal_drift", sa.Float(), nullable=True),
        sa.Column("is_game_anchor", sa.Boolean(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_calibrations_video_id"), "field_calibrations", ["video_id"], unique=False
    )
    op.create_table(
        "tracklets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("track_confidence", sa.Float(), nullable=True),
        sa.Column("team_label", sa.String(length=20), nullable=True),
        sa.Column("position_group", sa.String(length=20), nullable=True),
        sa.Column("side_of_ball", sa.String(length=10), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracklets_clip_id"), "tracklets", ["clip_id"], unique=False)
    op.create_table(
        "labels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=True),
        sa.Column("tracklet_id", sa.UUID(), nullable=True),
        sa.Column("label_type", sa.String(length=100), nullable=False),
        sa.Column("label_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("annotated_by", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("training_dataset_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["annotated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tracklet_id"], ["tracklets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["training_dataset_id"], ["training_datasets.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_clip_id"), "labels", ["clip_id"], unique=False)
    op.create_table(
        "metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("tracklet_id", sa.UUID(), nullable=True),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("is_suppressed", sa.Boolean(), nullable=False),
        sa.Column("suppression_reason", sa.Text(), nullable=True),
        sa.Column("experimental_flag", sa.Boolean(), nullable=False),
        sa.Column("analytics_safe", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("effort_zscore", sa.Float(), nullable=True),
        sa.Column("loaf_flag", sa.Boolean(), nullable=True),
        sa.Column("sprint_count", sa.Integer(), nullable=True),
        sa.Column("asymmetry_index", sa.Float(), nullable=True),
        sa.Column("injury_risk_score", sa.Float(), nullable=True),
        sa.Column("evidence_uri", sa.Text(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("calibration_version_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calibration_version_id"], ["field_calibrations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tracklet_id"], ["tracklets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metrics_clip_id"), "metrics", ["clip_id"], unique=False)
    op.create_index(op.f("ix_metrics_metric_name"), "metrics", ["metric_name"], unique=False)
    op.create_index(op.f("ix_metrics_tracklet_id"), "metrics", ["tracklet_id"], unique=False)
    op.create_table(
        "playembeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("chunk_kind", sa.String(length=20), nullable=False),
        sa.Column("snap_anchor", sa.Boolean(), nullable=False),
        sa.Column("vector", app.types.Vector(256), nullable=False),
        sa.Column("visual_vector", app.types.Vector(192), nullable=True),
        sa.Column("structured_vector", app.types.Vector(64), nullable=True),
        sa.Column("clip_vector", app.types.Vector(512), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("calibration_version_id", sa.UUID(), nullable=True),
        sa.Column("source_label_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("used_sam_masks", sa.Boolean(), nullable=False),
        sa.Column("embedding_confidence", sa.Float(), nullable=True),
        sa.Column("is_experimental", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calibration_version_id"], ["field_calibrations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "clip_id",
            "chunk_kind",
            "model_version_id",
            name="uq_playembeddings_clip_chunk_modelversion",
        ),
    )
    op.create_index(op.f("ix_playembeddings_clip_id"), "playembeddings", ["clip_id"], unique=False)
    op.create_index(
        op.f("ix_playembeddings_model_version_id"),
        "playembeddings",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        "playembeddings_clip_vector_ivfflat",
        "playembeddings",
        ["clip_vector"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_ops={"clip_vector": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    op.create_index(
        "playembeddings_vector_ivfflat",
        "playembeddings",
        ["vector"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_ops={"vector": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    op.create_table(
        "pose_keypoints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracklet_id", sa.UUID(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("keypoints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("head_yaw_degrees", sa.Float(), nullable=True),
        sa.Column("head_orientation_confidence", sa.Float(), nullable=True),
        sa.Column("biomechanics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["processing_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tracklet_id"], ["tracklets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pose_keypoints_tracklet_frame",
        "pose_keypoints",
        ["tracklet_id", "frame_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pose_keypoints_tracklet_id"), "pose_keypoints", ["tracklet_id"], unique=False
    )
    op.create_table(
        "track_points",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracklet_id", sa.UUID(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("field_x", sa.Float(), nullable=True),
        sa.Column("field_y", sa.Float(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detection_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["tracklet_id"], ["tracklets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_track_points_tracklet_id"), "track_points", ["tracklet_id"], unique=False
    )
    op.create_table(
        "head_orientation_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("review_action", sa.String(length=20), nullable=False),
        sa.Column("position_group", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["metric_id"], ["metrics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_head_orientation_reviews_metric_id"),
        "head_orientation_reviews",
        ["metric_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # The two cycle-breaking foreign keys. These are declared ``use_alter=True``
    # on the model, so they are deliberately absent from the CREATE TABLE above
    # and added here, once both ends exist. Autogenerate does not emit them --
    # it drops them from create_table without adding the follow-up ALTER -- so
    # they are maintained by hand. Without them, clips.job_id and
    # clips.calibration_version_id would be unconstrained columns.
    op.create_foreign_key(
        "clips_job_id_fkey",
        "clips",
        "processing_jobs",
        ["job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "clips_calibration_version_id_fkey",
        "clips",
        "field_calibrations",
        ["calibration_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Drop the cycle-breaking FKs first so the tables below can be dropped in
    # dependency order.
    op.drop_constraint("clips_calibration_version_id_fkey", "clips", type_="foreignkey")
    op.drop_constraint("clips_job_id_fkey", "clips", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_head_orientation_reviews_metric_id"), table_name="head_orientation_reviews"
    )
    op.drop_table("head_orientation_reviews")
    op.drop_index(op.f("ix_track_points_tracklet_id"), table_name="track_points")
    op.drop_table("track_points")
    op.drop_index(op.f("ix_pose_keypoints_tracklet_id"), table_name="pose_keypoints")
    op.drop_index("ix_pose_keypoints_tracklet_frame", table_name="pose_keypoints")
    op.drop_table("pose_keypoints")
    op.drop_index(
        "playembeddings_vector_ivfflat",
        table_name="playembeddings",
        postgresql_using="ivfflat",
        postgresql_ops={"vector": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    op.drop_index(
        "playembeddings_clip_vector_ivfflat",
        table_name="playembeddings",
        postgresql_using="ivfflat",
        postgresql_ops={"clip_vector": "vector_cosine_ops"},
        postgresql_with={"lists": 100},
    )
    op.drop_index(op.f("ix_playembeddings_model_version_id"), table_name="playembeddings")
    op.drop_index(op.f("ix_playembeddings_clip_id"), table_name="playembeddings")
    op.drop_table("playembeddings")
    op.drop_index(op.f("ix_metrics_tracklet_id"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_metric_name"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_clip_id"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("ix_labels_clip_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_tracklets_clip_id"), table_name="tracklets")
    op.drop_table("tracklets")
    op.drop_index(op.f("ix_field_calibrations_video_id"), table_name="field_calibrations")
    op.drop_table("field_calibrations")
    op.drop_index(op.f("ix_alerts_session_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_position_group"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_player_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_clip_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_active_learning_queue_label_type"), table_name="active_learning_queue")
    op.drop_index(op.f("ix_active_learning_queue_clip_id"), table_name="active_learning_queue")
    op.drop_table("active_learning_queue")
    op.drop_index(op.f("ix_processing_jobs_video_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_pipeline_mode"), table_name="processing_jobs")
    op.drop_index(
        "ix_processing_jobs_claim",
        table_name="processing_jobs",
        postgresql_where=sa.text("status = 'queued'::job_status"),
    )
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_play_predictions_opponent_team"), table_name="play_predictions")
    op.drop_index(op.f("ix_play_predictions_clip_id"), table_name="play_predictions")
    op.drop_table("play_predictions")
    op.drop_index(op.f("ix_play_concepts_concept_id"), table_name="play_concepts")
    op.drop_index(op.f("ix_play_concepts_clip_id"), table_name="play_concepts")
    op.drop_table("play_concepts")
    op.drop_index(op.f("ix_events_clip_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_coach_corrections_clip_id"), table_name="coach_corrections")
    op.drop_table("coach_corrections")
    op.drop_table("clip_players")
    op.drop_index(op.f("ix_assignment_scores_concept_id"), table_name="assignment_scores")
    op.drop_index(op.f("ix_assignment_scores_clip_id"), table_name="assignment_scores")
    op.drop_table("assignment_scores")
    op.drop_index(
        op.f("ix_player_profile_snapshots_week_start"), table_name="player_profile_snapshots"
    )
    op.drop_index(
        op.f("ix_player_profile_snapshots_profile_id"), table_name="player_profile_snapshots"
    )
    op.drop_index(
        op.f("ix_player_profile_snapshots_player_id"), table_name="player_profile_snapshots"
    )
    op.drop_table("player_profile_snapshots")
    op.drop_index(
        op.f("ix_embedding_cluster_proposals_status"), table_name="embedding_cluster_proposals"
    )
    op.drop_table("embedding_cluster_proposals")
    op.drop_index(op.f("ix_clips_video_id"), table_name="clips")
    op.drop_index(op.f("ix_clips_uncertainty_score"), table_name="clips")
    op.drop_index(op.f("ix_clips_side_of_ball"), table_name="clips")
    op.drop_index(op.f("ix_clips_session_kind"), table_name="clips")
    op.drop_index(op.f("ix_clips_result_state"), table_name="clips")
    op.drop_index(op.f("ix_clips_play_call_id"), table_name="clips")
    op.drop_index(op.f("ix_clips_capture_regime"), table_name="clips")
    op.drop_table("clips")
    op.drop_index(op.f("ix_wellness_entries_player_id"), table_name="wellness_entries")
    op.drop_index(op.f("ix_wellness_entries_date"), table_name="wellness_entries")
    op.drop_table("wellness_entries")
    op.drop_index(op.f("ix_sc_sessions_player_id"), table_name="sc_sessions")
    op.drop_index(op.f("ix_sc_sessions_date"), table_name="sc_sessions")
    op.drop_table("sc_sessions")
    op.drop_index(op.f("ix_player_workload_daily_player_id"), table_name="player_workload_daily")
    op.drop_index(op.f("ix_player_workload_daily_date"), table_name="player_workload_daily")
    op.drop_table("player_workload_daily")
    op.drop_index(
        op.f("ix_player_visibility_audit_player_id"), table_name="player_visibility_audit"
    )
    op.drop_table("player_visibility_audit")
    op.drop_index(op.f("ix_player_profiles_player_id"), table_name="player_profiles")
    op.drop_table("player_profiles")
    op.drop_index(op.f("ix_model_versions_model_name"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_injury_history_reported_date"), table_name="injury_history")
    op.drop_index(op.f("ix_injury_history_player_id"), table_name="injury_history")
    op.drop_table("injury_history")
    op.drop_index(op.f("ix_gps_workload_daily_player_id"), table_name="gps_workload_daily")
    op.drop_index(op.f("ix_gps_workload_daily_date"), table_name="gps_workload_daily")
    op.drop_table("gps_workload_daily")
    op.drop_index(op.f("ix_videos_session_kind"), table_name="videos")
    op.drop_index(op.f("ix_videos_recorded_at"), table_name="videos")
    op.drop_index(op.f("ix_videos_practice_session_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_opponent_team"), table_name="videos")
    op.drop_index(op.f("ix_videos_capture_regime"), table_name="videos")
    op.drop_table("videos")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_training_datasets_model_scope"), table_name="training_datasets")
    op.drop_table("training_datasets")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_report_jobs_requested_by"), table_name="report_jobs")
    op.drop_index(op.f("ix_report_jobs_report_type"), table_name="report_jobs")
    op.drop_index(op.f("ix_report_jobs_created_at"), table_name="report_jobs")
    op.drop_table("report_jobs")
    op.drop_index(op.f("ix_players_position_group"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_playbook_concepts_name"), table_name="playbook_concepts")
    op.drop_table("playbook_concepts")
    op.drop_index(op.f("ix_academic_calendar_events_date"), table_name="academic_calendar_events")
    op.drop_table("academic_calendar_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_opponent_priors_opponent_team"), table_name="opponent_priors")
    op.drop_table("opponent_priors")
    op.drop_index(op.f("ix_cfbd_win_probability_play_id"), table_name="cfbd_win_probability")
    op.drop_index(op.f("ix_cfbd_win_probability_cfbd_game_id"), table_name="cfbd_win_probability")
    op.drop_table("cfbd_win_probability")
    op.drop_index(op.f("ix_cfbd_teams_school"), table_name="cfbd_teams")
    op.drop_index(op.f("ix_cfbd_teams_conference"), table_name="cfbd_teams")
    op.drop_index(op.f("ix_cfbd_teams_cfbd_team_id"), table_name="cfbd_teams")
    op.drop_table("cfbd_teams")
    op.drop_index(op.f("ix_cfbd_team_game_stats_team"), table_name="cfbd_team_game_stats")
    op.drop_index(op.f("ix_cfbd_team_game_stats_season"), table_name="cfbd_team_game_stats")
    op.drop_index(op.f("ix_cfbd_team_game_stats_opponent"), table_name="cfbd_team_game_stats")
    op.drop_index(op.f("ix_cfbd_team_game_stats_conference"), table_name="cfbd_team_game_stats")
    op.drop_index(op.f("ix_cfbd_team_game_stats_cfbd_game_id"), table_name="cfbd_team_game_stats")
    op.drop_table("cfbd_team_game_stats")
    op.drop_index(op.f("ix_cfbd_sync_runs_season"), table_name="cfbd_sync_runs")
    op.drop_index(op.f("ix_cfbd_sync_runs_endpoint"), table_name="cfbd_sync_runs")
    op.drop_table("cfbd_sync_runs")
    op.drop_index(op.f("ix_cfbd_plays_week"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_season"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_offense"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_defense"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_cfbd_play_id"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_cfbd_game_id"), table_name="cfbd_plays")
    op.drop_index(op.f("ix_cfbd_plays_cfbd_drive_id"), table_name="cfbd_plays")
    op.drop_table("cfbd_plays")
    op.drop_index(op.f("ix_cfbd_games_week"), table_name="cfbd_games")
    op.drop_index(op.f("ix_cfbd_games_season_type"), table_name="cfbd_games")
    op.drop_index(op.f("ix_cfbd_games_season"), table_name="cfbd_games")
    op.drop_index(op.f("ix_cfbd_games_home_team"), table_name="cfbd_games")
    op.drop_index(op.f("ix_cfbd_games_cfbd_game_id"), table_name="cfbd_games")
    op.drop_index(op.f("ix_cfbd_games_away_team"), table_name="cfbd_games")
    op.drop_table("cfbd_games")
    op.drop_index(op.f("ix_cfbd_drives_season"), table_name="cfbd_drives")
    op.drop_index(op.f("ix_cfbd_drives_offense"), table_name="cfbd_drives")
    op.drop_index(op.f("ix_cfbd_drives_defense"), table_name="cfbd_drives")
    op.drop_index(op.f("ix_cfbd_drives_cfbd_game_id"), table_name="cfbd_drives")
    op.drop_index(op.f("ix_cfbd_drives_cfbd_drive_id"), table_name="cfbd_drives")
    op.drop_table("cfbd_drives")

    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
    # The pgvector extension is deliberately left in place: other schemas in
    # the same database may depend on it, and re-creating it is cheap.
